#  ############################################################################# #
#  Author       : dmike
#  Date         : 2,October 2016
#  Description  : Principal Make file
#
#  Default KBUILD file that does not define only the language variable.
#  Setting it to 'cc'.
#
#  ############################################################################# #
languages := packages packages/pack1/ packages/pack2/
install_language := pacakges
mode := color_
debug := @

#  ############################################################################# #
#  Command definition.
#  ############################################################################# #
CC := gcc
LD := ld
RM := rm
MKDIR:= mkdir
AR:= ar
RANLIB:= ranlib
DOCKER:= docker

export CC LD RM MKDIR AR RANLIB DOCKER